# Generated by Django 5.2.4 on 2025-12-13 11:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('location', '0001_initial'),
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('listing_type', models.CharField(choices=[('PRODUCT', 'Product'), ('SERVICE', 'Service')], max_length=20)),
                ('price_type', models.CharField(choices=[('FIXED', 'Fixed'), ('RANGE', 'Range'), ('ON_REQUEST', 'On Request')], max_length=20)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='UGX', max_length=3)),
                ('is_price_negotiable', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed'), ('DEACTIVATED', 'Deactivated'), ('REJECTED', 'Rejected')], db_index=True, default='DRAFT', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('featured_until', models.DateTimeField(blank=True, null=True)),
                ('views_count', models.IntegerField(default=0)),
                ('contact_count', models.IntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='categories.category')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='location.location')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='merchants.merchant')),
            ],
            options={
                'db_table': 'listings',
            },
        ),
        migrations.CreateModel(
            name='ListingTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.listing')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.tag')),
            ],
            options={
                'db_table': 'listing_tags',
            },
        ),
        migrations.AddField(
            model_name='listing',
            name='tags',
            field=models.ManyToManyField(related_name='listings', through='listings.ListingTag', to='categories.tag'),
        ),
        migrations.CreateModel(
            name='ListingBusinessHour',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3)),
                ('opens_at', models.TimeField()),
                ('closes_at', models.TimeField()),
                ('is_closed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_hours', to='listings.listing')),
            ],
            options={
                'db_table': 'listing_business_hours',
                'indexes': [models.Index(fields=['listing'], name='listing_bus_listing_da7931_idx'), models.Index(fields=['day'], name='listing_bus_day_117464_idx')],
            },
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.URLField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.listing')),
            ],
            options={
                'db_table': 'listing_images',
                'ordering': ['sort_order'],
                'indexes': [models.Index(fields=['listing'], name='listing_ima_listing_d8bfd0_idx'), models.Index(fields=['is_primary'], name='listing_ima_is_prim_133559_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='listingtag',
            index=models.Index(fields=['listing'], name='listing_tag_listing_7992a2_idx'),
        ),
        migrations.AddIndex(
            model_name='listingtag',
            index=models.Index(fields=['tag'], name='listing_tag_tag_id_951683_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='listingtag',
            unique_together={('listing', 'tag')},
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['merchant'], name='listings_merchan_a12c3b_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['category'], name='listings_categor_de1c95_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['location'], name='listings_locatio_a1eef8_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['status'], name='listings_status_c3eaec_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['is_featured'], name='listings_is_feat_01aa9f_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['created_at'], name='listings_created_ac7d1b_idx'),
        ),
    ]
