# Generated by Django 5.2.4 on 2025-12-16 15:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('listings', '0001_initial'),
        ('location', '0001_initial'),
        ('merchants', '0003_merchant_featured_merchant_featured_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='listingbusinesshour',
            options={'ordering': ['day']},
        ),
        migrations.AlterModelOptions(
            name='listingimage',
            options={'ordering': ['sort_order', 'created_at']},
        ),
        migrations.RemoveIndex(
            model_name='listing',
            name='listings_merchan_a12c3b_idx',
        ),
        migrations.RemoveIndex(
            model_name='listing',
            name='listings_categor_de1c95_idx',
        ),
        migrations.RemoveIndex(
            model_name='listing',
            name='listings_locatio_a1eef8_idx',
        ),
        migrations.RemoveIndex(
            model_name='listing',
            name='listings_status_c3eaec_idx',
        ),
        migrations.RemoveIndex(
            model_name='listing',
            name='listings_is_feat_01aa9f_idx',
        ),
        migrations.RemoveIndex(
            model_name='listing',
            name='listings_created_ac7d1b_idx',
        ),
        migrations.RemoveIndex(
            model_name='listingimage',
            name='listing_ima_listing_d8bfd0_idx',
        ),
        migrations.RemoveIndex(
            model_name='listingimage',
            name='listing_ima_is_prim_133559_idx',
        ),
        migrations.AddField(
            model_name='listing',
            name='featured_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='contact_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='listing',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Review'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed'), ('DEACTIVATED', 'Deactivated'), ('REJECTED', 'Rejected')], db_index=True, default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='listing',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='listingbusinesshour',
            name='closes_at',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listingbusinesshour',
            name='opens_at',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listingimage',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='listingbusinesshour',
            unique_together={('listing', 'day')},
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['merchant', 'status'], name='listings_merchan_5a94ff_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['category', 'status'], name='listings_categor_7f7673_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['location', 'status'], name='listings_locatio_46ea0f_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['is_verified', 'status'], name='listings_is_veri_d7a7f9_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['is_featured', 'is_verified', 'status'], name='listings_is_feat_fbb0ed_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['-created_at'], name='listings_created_4615f6_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['listing_type', 'status'], name='listings_listing_56bbe5_idx'),
        ),
        migrations.AddIndex(
            model_name='listingimage',
            index=models.Index(fields=['listing', 'is_primary'], name='listing_ima_listing_7b284b_idx'),
        ),
        migrations.AddIndex(
            model_name='listingimage',
            index=models.Index(fields=['listing', 'sort_order'], name='listing_ima_listing_f22559_idx'),
        ),
    ]
