# Generated by Django 5.2.4 on 2025-12-16 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_listing_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='listing',
            name='listings_locatio_46ea0f_idx',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='location',
        ),
    ]
