# Generated by Django 5.2.4 on 2026-01-06 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_remove_listing_listings_locatio_46ea0f_idx_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListingImage',
        ),
    ]
