# Generated by Django 5.2.4 on 2026-01-07 03:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_group_id', models.UUIDField(db_index=True)),
                ('object_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('image_type', models.CharField(choices=[('listing', 'Listing'), ('profile', 'Profile'), ('store_banner', 'Store Banner'), ('store_cover', 'Store Cover')], max_length=20)),
                ('variant', models.CharField(choices=[('thumb', 'Thumbnail'), ('medium', 'Medium'), ('large', 'Large')], max_length=20)),
                ('s3_key', models.CharField(max_length=500, unique=True)),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('size_bytes', models.PositiveIntegerField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'image_assets',
                'indexes': [models.Index(fields=['image_type', 'object_id'], name='image_asset_image_t_4f4fd3_idx'), models.Index(fields=['image_group_id'], name='image_asset_image_g_695aa3_idx'), models.Index(fields=['owner', 'is_confirmed', 'object_id'], name='image_asset_owner_i_9a1834_idx'), models.Index(fields=['created_at'], name='image_asset_created_6e20d0_idx')],
                'unique_together': {('image_group_id', 'variant')},
            },
        ),
    ]
