# Generated by Django 5.2.4 on 2026-01-06 21:25

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagehandler', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='imageasset',
            name='image_group_id',
            field=models.UUIDField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='imageasset',
            name='object_id',
            field=models.UUIDField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='imageasset',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='imageasset',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='imageasset',
            name='variant',
            field=models.CharField(choices=[('thumb', 'Thumbnail'), ('medium', 'Medium'), ('large', 'Large')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='imageasset',
            unique_together={('image_group_id', 'variant')},
        ),
        migrations.AddIndex(
            model_name='imageasset',
            index=models.Index(fields=['image_type', 'object_id'], name='imagehandle_image_t_d63c0a_idx'),
        ),
        migrations.AddIndex(
            model_name='imageasset',
            index=models.Index(fields=['image_group_id'], name='imagehandle_image_g_4070b3_idx'),
        ),
    ]
