# Generated by Django 5.2.4 on 2025-12-13 11:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=255)),
                ('business_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('business_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('business_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('logo', models.URLField(blank=True, null=True)),
                ('cover_image', models.URLField(blank=True, null=True)),
                ('verified', models.BooleanField(db_index=True, default=False)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('rating', models.FloatField(db_index=True, default=0.0)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('BANNED', 'Banned')], db_index=True, default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'merchants',
                'indexes': [models.Index(fields=['user'], name='merchants_user_id_d9e4a7_idx'), models.Index(fields=['verified'], name='merchants_verifie_2be6a0_idx'), models.Index(fields=['status'], name='merchants_status_c90f29_idx'), models.Index(fields=['rating'], name='merchants_rating_07237e_idx')],
            },
        ),
    ]
