# Generated by Django 5.2.4 on 2025-12-16 07:23

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='merchant',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='merchant',
            name='merchants_verifie_2be6a0_idx',
        ),
        migrations.RemoveIndex(
            model_name='merchant',
            name='merchants_status_c90f29_idx',
        ),
        migrations.RemoveIndex(
            model_name='merchant',
            name='merchants_rating_07237e_idx',
        ),
        migrations.AddField(
            model_name='merchant',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='merchant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='business_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='display_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='rating',
            field=models.FloatField(db_index=True, default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AddIndex(
            model_name='merchant',
            index=models.Index(fields=['verified', 'status'], name='merchants_verifie_da817d_idx'),
        ),
        migrations.AddIndex(
            model_name='merchant',
            index=models.Index(fields=['-rating', 'display_name'], name='merchants_rating_a0c2ae_idx'),
        ),
        migrations.AddIndex(
            model_name='merchant',
            index=models.Index(fields=['-created_at'], name='merchants_created_76885b_idx'),
        ),
    ]
