# Generated by Django 5.2.4 on 2025-12-16 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('merchants', '0003_merchant_featured_merchant_featured_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='location.location'),
        ),
    ]
