# Generated by Django 5.2.4 on 2026-04-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_alter_location_latitude_alter_location_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
