# Generated by Django 5.2.4 on 2025-12-14 15:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('intent_completed', models.BooleanField(default=False)),
                ('categories_completed', models.BooleanField(default=False)),
                ('profile_completed', models.BooleanField(default=False)),
                ('is_onboarding_complete', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_status', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Onboarding Status',
                'verbose_name_plural': 'Onboarding Statuses',
                'db_table': 'onboarding_statuses',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['is_onboarding_complete'], name='onboarding__is_onbo_559de9_idx'), models.Index(fields=['-updated_at'], name='onboarding__updated_5e6445_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserIntent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('intent', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('both', 'Both')], help_text="User's marketplace intent", max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='User associated with this intent', on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_intent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Intent',
                'verbose_name_plural': 'User Intents',
                'db_table': 'user_intents',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['intent'], name='user_intent_intent_3cee4d_idx'), models.Index(fields=['-updated_at'], name='user_intent_updated_64cb32_idx')],
            },
        ),
    ]
