# Generated by Django 5.2.4 on 2025-12-14 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0002_onboardingstatus_userintent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PushToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=200, unique=True)),
                ('device_id', models.CharField(blank=True, max_length=100)),
                ('platform', models.CharField(blank=True, choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'push_tokens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='push_tokens_user_id_3067f6_idx'), models.Index(fields=['token'], name='push_tokens_token_c43621_idx'), models.Index(fields=['last_used'], name='push_tokens_last_us_10d99d_idx')],
                'unique_together': {('user', 'device_id')},
            },
        ),
    ]
