# Generated by Django 5.2.4 on 2025-12-17 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0003_pushtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
