# Generated by Django 5.2.4 on 2025-12-28 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0004_delete_favorite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
