# Generated by Django 5.2.4 on 2026-04-11 21:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0005_delete_notification'),
        ('listings', '0004_delete_listingimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='listings.listing')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='engagement.listingcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'listing_comments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['listing', 'is_deleted'], name='listing_com_listing_b472fb_idx'), models.Index(fields=['user'], name='listing_com_user_id_0cbf18_idx'), models.Index(fields=['parent'], name='listing_com_parent__b06835_idx'), models.Index(fields=['created_at'], name='listing_com_created_454eff_idx')],
            },
        ),
    ]
