# Generated by Django 5.2.4 on 2025-12-13 11:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionalCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('campaign_type', models.CharField(choices=[('FEATURED_LISTING', 'Featured Listing'), ('BANNER', 'Banner'), ('PUSH_NOTIFICATION', 'Push Notification'), ('EMAIL', 'Email')], max_length=30)),
                ('start_date', models.DateTimeField(db_index=True)),
                ('end_date', models.DateTimeField(db_index=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed')], db_index=True, default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'promotional_campaigns',
                'indexes': [models.Index(fields=['status'], name='promotional_status_b1efda_idx'), models.Index(fields=['start_date'], name='promotional_start_d_9d26dd_idx'), models.Index(fields=['end_date'], name='promotional_end_dat_a12cb1_idx')],
            },
        ),
        migrations.CreateModel(
            name='CampaignCreative',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creative_type', models.CharField(choices=[('SLIDER', 'Slider'), ('BANNER', 'Banner'), ('POPUP', 'Popup')], db_index=True, max_length=20)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('image', models.URLField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('platform', models.CharField(choices=[('ANDROID', 'Android'), ('IOS', 'iOS'), ('WEB', 'Web'), ('ALL', 'All Platforms')], db_index=True, default='ALL', max_length=20)),
                ('cta_text', models.CharField(blank=True, max_length=50)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creatives', to='promotions.promotionalcampaign')),
            ],
            options={
                'db_table': 'campaign_creatives',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='CampaignPlacement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('placement', models.CharField(choices=[('HOME_TOP', 'Home Top Slider'), ('HOME_MIDDLE', 'Home Middle Banner'), ('HOME_BOTTOM', 'Home Bottom Banner'), ('CATEGORY', 'Category Page'), ('LISTING', 'Listing Page'), ('SEARCH', 'Search Results')], db_index=True, max_length=30)),
                ('target_type', models.CharField(choices=[('LISTING', 'Listing'), ('CATEGORY', 'Category'), ('MERCHANT', 'Merchant'), ('URL', 'External URL'), ('NONE', 'No Action')], default='NONE', max_length=20)),
                ('target_id', models.UUIDField(blank=True, null=True)),
                ('target_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='promotions.campaigncreative')),
            ],
            options={
                'db_table': 'campaign_placements',
                'indexes': [models.Index(fields=['placement'], name='campaign_pl_placeme_0e145c_idx'), models.Index(fields=['target_type'], name='campaign_pl_target__f89573_idx')],
            },
        ),
        migrations.CreateModel(
            name='CampaignListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('impressions', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('conversions', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='listings.listing')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='promotions.promotionalcampaign')),
            ],
            options={
                'db_table': 'campaign_listings',
                'indexes': [models.Index(fields=['campaign'], name='campaign_li_campaig_b9d6e8_idx'), models.Index(fields=['listing'], name='campaign_li_listing_2700e5_idx')],
                'unique_together': {('campaign', 'listing')},
            },
        ),
        migrations.AddIndex(
            model_name='campaigncreative',
            index=models.Index(fields=['creative_type'], name='campaign_cr_creativ_e61727_idx'),
        ),
        migrations.AddIndex(
            model_name='campaigncreative',
            index=models.Index(fields=['platform'], name='campaign_cr_platfor_d93c46_idx'),
        ),
        migrations.AddIndex(
            model_name='campaigncreative',
            index=models.Index(fields=['is_active'], name='campaign_cr_is_acti_022361_idx'),
        ),
    ]
