# Generated by Django 5.2.4 on 2025-12-16 06:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('listings', '0001_initial'),
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignplacement',
            name='creative',
        ),
        migrations.AlterUniqueTogether(
            name='campaignlisting',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='campaignlisting',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='campaignlisting',
            name='listing',
        ),
        migrations.CreateModel(
            name='PromotionalBanner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('display_type', models.CharField(choices=[('CAROUSEL', 'Carousel/Slider'), ('BANNER', 'Banner'), ('AD', 'Advertisement')], max_length=20)),
                ('placement', models.CharField(choices=[('HOME_TOP', 'Home Page - Top'), ('HOME_MIDDLE', 'Home Page - Middle'), ('CATEGORY_TOP', 'Category Page - Top'), ('SEARCH_TOP', 'Search Results - Top')], max_length=30)),
                ('platform', models.CharField(choices=[('ALL', 'All Platforms'), ('WEB', 'Web Only'), ('MOBILE', 'Mobile Only'), ('ANDROID', 'Android Only'), ('IOS', 'iOS Only')], default='ALL', max_length=20)),
                ('image', models.URLField(help_text='Main banner image URL')),
                ('mobile_image', models.URLField(blank=True, help_text='Optional mobile-specific image')),
                ('link_type', models.CharField(choices=[('LISTING', 'Single Listing'), ('LISTINGS', 'Multiple Listings'), ('CATEGORY', 'Category'), ('URL', 'External URL'), ('NONE', 'No Link')], default='NONE', max_length=20)),
                ('link_url', models.URLField(blank=True, help_text='For external URLs')),
                ('cta_text', models.CharField(blank=True, help_text='Call to action text', max_length=50)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.IntegerField(default=0, help_text='Lower numbers appear first')),
                ('impressions', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('link_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotional_banners', to='categories.category')),
            ],
            options={
                'db_table': 'promotional_banners',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BannerListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotional_banners', to='listings.listing')),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_listings', to='promotions.promotionalbanner')),
            ],
            options={
                'db_table': 'banner_listings',
                'ordering': ['sort_order'],
            },
        ),
        migrations.DeleteModel(
            name='CampaignCreative',
        ),
        migrations.DeleteModel(
            name='CampaignPlacement',
        ),
        migrations.DeleteModel(
            name='PromotionalCampaign',
        ),
        migrations.DeleteModel(
            name='CampaignListing',
        ),
        migrations.AddIndex(
            model_name='promotionalbanner',
            index=models.Index(fields=['placement', 'is_active', 'is_verified'], name='promotional_placeme_f3491c_idx'),
        ),
        migrations.AddIndex(
            model_name='promotionalbanner',
            index=models.Index(fields=['start_date', 'end_date'], name='promotional_start_d_851252_idx'),
        ),
        migrations.AddIndex(
            model_name='promotionalbanner',
            index=models.Index(fields=['display_type'], name='promotional_display_68185b_idx'),
        ),
        migrations.AddIndex(
            model_name='promotionalbanner',
            index=models.Index(fields=['platform'], name='promotional_platfor_6afd91_idx'),
        ),
        migrations.AddIndex(
            model_name='bannerlisting',
            index=models.Index(fields=['banner', 'sort_order'], name='banner_list_banner__333a36_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bannerlisting',
            unique_together={('banner', 'listing')},
        ),
    ]
