# Generated by Django 5.2.4 on 2025-12-13 11:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='UGX', max_length=3)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('MOBILE_MONEY', 'Mobile Money'), ('BANK_TRANSFER', 'Bank Transfer'), ('CARD', 'Card')], max_length=20)),
                ('payment_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], db_index=True, default='PENDING', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_intent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='orders.orderintent')),
            ],
            options={
                'db_table': 'transactions',
                'indexes': [models.Index(fields=['order_intent'], name='transaction_order_i_4f5b10_idx'), models.Index(fields=['status'], name='transaction_status_505a2f_idx'), models.Index(fields=['transaction_number'], name='transaction_transac_b11dd9_idx')],
            },
        ),
    ]
