# Generated by Django 5.2.4 on 2025-12-13 11:06

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        ('location', '0001_initial'),
        ('merchants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderIntent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('delivery_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='NEW', max_length=20)),
                ('cancelled_by', models.CharField(blank=True, choices=[('BUYER', 'Buyer'), ('MERCHANT', 'Merchant'), ('ADMIN', 'Admin')], max_length=20, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='location.useraddress')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='merchants.merchant')),
            ],
            options={
                'db_table': 'order_intents',
            },
        ),
        migrations.CreateModel(
            name='OrderIntentItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='listings.listing')),
                ('order_intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.orderintent')),
            ],
            options={
                'db_table': 'order_intent_items',
            },
        ),
        migrations.AddIndex(
            model_name='orderintent',
            index=models.Index(fields=['buyer'], name='order_inten_buyer_i_ff8a53_idx'),
        ),
        migrations.AddIndex(
            model_name='orderintent',
            index=models.Index(fields=['merchant'], name='order_inten_merchan_767c26_idx'),
        ),
        migrations.AddIndex(
            model_name='orderintent',
            index=models.Index(fields=['status'], name='order_inten_status_39663f_idx'),
        ),
        migrations.AddIndex(
            model_name='orderintent',
            index=models.Index(fields=['order_number'], name='order_inten_order_n_1dea9b_idx'),
        ),
        migrations.AddIndex(
            model_name='orderintent',
            index=models.Index(fields=['created_at'], name='order_inten_created_64bc9f_idx'),
        ),
        migrations.AddIndex(
            model_name='orderintentitem',
            index=models.Index(fields=['order_intent'], name='order_inten_order_i_12ed46_idx'),
        ),
        migrations.AddIndex(
            model_name='orderintentitem',
            index=models.Index(fields=['listing'], name='order_inten_listing_c87735_idx'),
        ),
    ]
