# Generated by Django 5.2.4 on 2025-12-27 04:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'order_groups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='orderintent',
            name='order_group',
            field=models.ForeignKey(blank=True, help_text='Links orders that were placed together in one checkout', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.ordergroup'),
        ),
        migrations.AddIndex(
            model_name='ordergroup',
            index=models.Index(fields=['buyer', '-created_at'], name='order_group_buyer_i_8177a2_idx'),
        ),
        migrations.AddIndex(
            model_name='ordergroup',
            index=models.Index(fields=['group_number'], name='order_group_group_n_ecb621_idx'),
        ),
    ]
